version: "3.1"
services:

  # api:
  #   build: . -f <<Dockerfile>
  # depends_on: 
  #   database
  

  database: #user:root, password:example
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: api-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #  ./mariadb_data:/var/lib/mariadb/data
    ports:
      - 8083:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#volumes:
    #mariadb_data: