### health
GET http://localhost:8081/health HTTP/1.1

### create estudiante
POST http://localhost:8081/apiv1/estudiante/ HTTP/1.1
Content-Type: application/json

{    
    "id": 101,
    "nombre": "Carla Estrella",
    "telefono": "809-581-9876",
    "fecha_nacimiento": "01-01-1997"
}

### update user
PUT http://localhost:8081/apiv1/estudiante/ HTTP/1.1
Content-Type: application/json

{    
    "id": 100,
    "nombre": "Andres Perez",
    "telefono": "809-581-1234",
    "fecha_nacimiento": "01-01-1999"
}

### get all estudiantes
GET http://localhost:8081/apiv1/estudiante/ HTTP/1.1

### get estudiante by ID
GET http://localhost:8081/apiv1/estudiante/100 HTTP/1.1


### delete estudiante
DELETE  http://localhost:8081/apiv1/estudiante/101 HTTP/1.1